### ISSUE TITLE
Is the update formula different from that in TPR paper?

### ISSUE THREAD

**Issue by JonathanChen1002** [cnclabs/codes.tpr.rec#1]
from source code for calculating gradient
https://github.com/cnclabs/codes.tpr.rec/blob/master/src/optimizer/triplet_optimizer.cpp#L28-L49
It seems that it use the formula below:
![image](https://user-images.githubusercontent.com/68215303/104568093-9201d000-568a-11eb-901d-7144ea57a5f1.png)
But from formula (9) in the TPR paper, the update formula is as following:
![image](https://user-images.githubusercontent.com/68215303/104568364-f886ee00-568a-11eb-81b9-ac7f5c4da5e7.png)
which is equal to:
![image](https://user-images.githubusercontent.com/68215303/104568583-3be15c80-568b-11eb-9678-1e76aaac1497.png)

I'm wondering if the implementation in this repo is different from original TPR paper?

**Comment by chihming** [comment]
The current version is indeed different from original TPR paper as we finally modify some parts before the code release. You can try to replace the current one by the conventional bpr loss. I believe it's still able to reproduce the results we reported in the paper.

**Comment by JonathanChen1002** [comment]
Actually I'm applying TPR on my own dataset. And I wish to monitor the curve of loss.
I'm curious about what loss function that was adopted in this repo? Is there any source of reference?
Thanks for your reply.

**Comment by chihming** [comment]
Since BPR gets only positive pairs, the current loss would be: log sigmoid ( prediction - margin ).

edit. this function is not exactly correct, see the comments in below

**Comment by JonathanChen1002** [comment]
> Since BPR gets only positive pairs, the current loss would be: log sigmoid ( prediction - margin ).

Is the meaning of "prediction" the same as that in the source code?
https://github.com/cnclabs/codes.tpr.rec/blob/master/src/optimizer/triplet_optimizer.cpp#L28-L49
It seems that the input for sigmoid function is -prediction (or -x+margin) rather than prediction - margin
Besides, I think the gradient should be 1 - sigmoid(prediction) 
Where did I get it wrong?

**Comment by chihming** [comment]
let me to explain it from this view:
the original loss is log sigmoid( prediction ), I add a margin in its gradient ( i.e. sigmoid(-prediction) ), for the purpose of learning it effective and efficient

**Comment by JonathanChen1002** [comment]
I've implemented a monitor to calculate batch loss (sigmoid(prediction)) and it looks fine.
Thanks a lot!
